296 add video
data-summit/data-summit pull request #28
Opened 2021-01-13 20:26 UTC by TomJamesAtDataSummit

Video location (padding) and text location corrected, so that any text content is centred over the video. Text content to be determined separately.

2021-01-14 00:12 UTC, robbhudl commented
You need to rebase this branch.

No way there should be 24 files changed to create a simple background video component

2021-01-15 12:34 UTC, TomJamesAtDataSummit commented
Fair enough. The 24 files are due to me branching from #27 (not master), which I know is **not** the correct method. Do you want me to undo all the un-related changes? If not, you'll have to show how to rebase, as there is a good chance that I will mess a lot of things.

2021-01-15 13:22 UTC, robbhudl requested changes

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/.eslintcache
> +[{"C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\index.tsx":"1","C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\reportWebVitals.ts":"2","C:\\GitHub\\data-summit\\DataSummitSolution\\ui
I think we should add this file to .gitignore. It serves us no purpose in the project

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/App.css
>    align-items: center;
Let's get these into a sass module file and be consistent with how we use css in the whole project. One way to rule them all!

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/App.tsx
> +import Video from './Components/BackgroundVideo/BackgroundVideo';
If the Component is `BackgroundVideo` keep the import name the same so that semantics are preserved and the code is easier to read, follow and understand

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/App.tsx
>  import './App.css';
Use a module

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +import testMP4 from './Test.mp4';
We should move this out and allow it to be passed into the component - I believe the A/C called out making it configurable

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +const BackgroundVideo = () => {
```suggestion
const BackgroundVideo = ({videoPath}) => {
```

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +                url={ testMP4 }
```suggestion
                url={ videoPath } 
```

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +        <div className={ styles.video } id="Video">
```suggestion
        <div className={ styles.video } id="BackgroundVideo">
```

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +                muted={true}
```suggestion
                muted= { true }
```

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +                height = '100%'
Pass these in as params to allow the component to be configurable

`width = { width }
  height = { height }

2021-01-15 13:22 UTC, robbhudl commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.module.scss
> +  }
nice work here.

`.video` could have a better name as I don't believe it applies to the video? I think it's more of a wrapper, no?

2021-01-15 13:33 UTC, robbhudl commented
> Fair enough. The 24 files are due to me branching from #27 (not master), which I know is **not** the correct method. Do you want me to undo all the un-related changes? If not, you'll have to show how to rebase, as there is a good chance that I will mess a lot of things.

I used the `Update from master` option in Github desktop to bring this branch into line. We can do a rebase session another time.

Review submitted, I'm keen for you to understand why I've requested those changes so please ask questions in the review thread if they don't make sense or you don't understand why. Or even if you disagree. Code review is 2-way

2021-01-18 15:14 UTC, robbhudl commented on DataSummitSolution/ui/src/App.tsx
> +import Video from './Components/BackgroundVideo/BackgroundVideo';
Updated import name

2021-01-18 20:10 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.module.scss
> +  }
Named changed to 'wrapper' for clarity.

2021-01-18 20:10 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +                height = '100%'
Done.

2021-01-18 20:10 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +                muted={true}
General React code formatting will persist from now on.

2021-01-18 20:11 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +                url={ testMP4 }
Video file path included within component parameters.

2021-01-18 20:12 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/src/App.tsx
>  import './App.css';
Modules now the default for any styles.

2021-01-18 20:12 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/src/Components/BackgroundVideo/BackgroundVideo.jsx
> +import testMP4 from './Test.mp4';
Video path now included within parameters.

2021-01-21 17:28 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/.eslintcache
> +[{"C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\index.tsx":"1","C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\reportWebVitals.ts":"2","C:\\GitHub\\data-summit\\DataSummitSolution\\ui
eslint added to '.gitignore' but push, pull and publish functions on GitHub desktop are not working.

2021-01-21 17:59 UTC, THEgaDJet commented
What do you mean by "not working"
What is happening?
What are you expecting to happen?

You need to be clearer so that I can attempt to help.

On Thu, 21 Jan 2021, 17:28 Tom James, <notifications@github.com> wrote:

> *@TomJamesAtDataSummit* commented on this pull request.
> ------------------------------
>
> In DataSummitSolution/ui/.eslintcache
> <https://github.com/data-summit/data-summit/pull/28#discussion_r562064521>
> :
>
> > \ No newline at end of file
> +[{"C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\index.tsx":"1","C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\reportWebVitals.ts":"2","C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\App.tsx":"3","C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\Components\\BackgroundVideo\\BackgroundVideo.jsx":"4"},{"size":500,"mtime":499162500000,"results":"5","hashOfConfig":"6"},{"size":425,"mtime":499162500000,"results":"7","hashOfConfig":"6"},{"size":506,"mtime":1610487633583,"results":"8","hashOfConfig":"6"},{"size":717,"mtime":1610569365628,"results":"9","hashOfConfig":"6"},{"filePath":"10","messages":"11","errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":"12"},"ttu3nw",{"filePath":"13","messages":"14","errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":"12"},{"filePath":"15","messages":"16","errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":"12"},{"filePath":"17","messages":"18","errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0},"C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\index.tsx",[],["19","20"],"C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\reportWebVitals.ts",[],"C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\App.tsx",[],"C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\Components\\BackgroundVideo\\BackgroundVideo.jsx",[],{"ruleId":"21","replacedBy":"22"},{"ruleId":"23","replacedBy":"24"},"no-native-reassign",["25"],"no-negated-in-lhs",["26"],"no-global-assign","no-unsafe-negation"]
>
> eslint added to '.gitignore' but push, pull and publish functions on
> GitHub desktop are not working.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/data-summit/data-summit/pull/28#discussion_r562064521>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADYMJDSIZWJJ7BAVE366VILS3BP3TANCNFSM4WBL35YA>
> .
>

2021-01-21 20:25 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/.eslintcache
> +[{"C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\index.tsx":"1","C:\\GitHub\\data-summit\\DataSummitSolution\\ui\\src\\reportWebVitals.ts":"2","C:\\GitHub\\data-summit\\DataSummitSolution\\ui
GitHub Desktop says that there are "Fetch" items on another computer that are needed prior to publishing again. Clicking on "Fetch" results in this error message:

> error: cannot lock ref 'refs/remotes/origin/296_Add_Video': unable to resolve reference 'refs/remotes/origin/296_Add_Video': reference broken
> From https://github.com/data-summit/data-summit
>  ! [new branch]      296_Add_Video -> origin/296_Add_Video  (unable to update local ref)
> error: cannot lock ref 'refs/remotes/origin/master': unable to resolve reference 'refs/remotes/origin/master': reference broken
>  ! [new branch]      master        -> origin/master  (unable to update local ref)

2021-01-21 20:26 UTC, TomJamesAtDataSummit commented on DataSummitSolution/ui/src/App.css
>    align-items: center;
Done

2021-04-03 15:54 UTC, closed without merging