468 API End-point for A4 Text Recoginition
data-summit/data-summit pull request #47
Opened 2021-06-17 17:35 UTC by TomJamesAtDataSummit

Initial pull request created.

2021-06-17 17:39 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Dto/ImageDimensionsDto.cs
> +    public class ImageDimensionsDto
Should this be a `public sealed class`?

2021-06-17 17:40 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Interfaces/IAzureResourcesService.cs
> +        Task<IDictionary<string, string>> GetBlobMetadata(string blobUrl);
`IDictionary<string, string>` is the default value, as per Microsoft. Should this be `List<KeyPairValue<string, string>>`

2021-06-17 17:51 UTC, TomJamesAtDataSummit reviewed
I left my initial thoughts here when some items could be handled different ways.

2021-06-17 17:51 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Interfaces/IDataSummitDocumentsService.cs
> +        Task<KeyValuePair<string, int>> GetDocumentText(string blobUrl);
Returns:
`string` = blobUrl
`int` = number of features detected

2021-06-17 17:51 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Interfaces/IDataSummitHelperService.cs
> +        Task<HttpResponseMessage> ProcessCall(Uri uri, string payload, Dictionary<string, string> headers);
Required when the `Key` is in the header and not a `URI` parameter

2021-06-17 17:51 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +        private readonly IAzureResourcesService _azureResourcesService;
`_azureResources` or `_azureResourcesService`?

2021-06-17 17:51 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +        public async Task<ImageDimensionsDto> GetDocumentImageDimensionsFromMetadata(string blobUrl)
Whilst potentially outside the scope of the User Story, this metadata isn't being created/added currently. This seemed the lowest overhead approach to storing/obtaining this type of information.

2021-06-17 17:51 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +            //TODO catch error responses
@THEgaDJet, can this error catch be added this time, so that I can implement it next time?

2021-06-17 17:51 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +            var detectedText = JsonConvert.DeserializeObject<DataSummitModels.Cloud.CognitiveServices.OCR.Application>(response);
I left this fully visible and not via `using`, sensible?

2021-06-18 17:57 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                var functionTasks = new List<DataSummitModels.DTO.FunctionTask>();
`var functionTasks = new List<FunctionTask>();`

2021-06-18 18:01 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                if (imgUp.Tasks?.Any() ?? true) return new BadRequestObjectResult("Illegal input: 'Tasks' list is null or empty");
Put this in a function

ValidateImage(imageUpload)

2021-06-18 18:02 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                  ImageUpload imgUp = (ImageUpload)data;
var imageUpload

2021-06-18 18:02 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                  dynamic data = JsonConvert.DeserializeObject<ImageUpload>(jsonContent,
I'm still not convinced this should be dynamic

2021-06-18 20:52 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                var ocrRes = new Document();
Name things properly

2021-06-18 20:54 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                                             ";AccountKey=" + imgUp.StorageAccountKey + ";EndpointSuffix=core.windows.net";
Use string interpolation $"{};{};{};"

2021-06-18 20:58 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                  if (blobClient.ToString() == "") { log.LogInformation(strError + ": failed"); }
You shouldn't be checking something by calling `.ToString()`

Also the lines 64 and 69 should use var 

Why are you logging an error if account != null? Lines 65 - 67 look completely unecessary

2021-06-18 20:59 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                functionTasks.Add(new DataSummitModels.DTO.FunctionTask("Azure OCR\tGet container", imgUp.Tasks[functionTasks.Count - 1].TimeStamp));
Get rid of `DataSummitModels.DTO`

2021-06-18 21:00 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                log.LogInformation(imgUp.Tasks[functionTasks.Count - 1].Name + ":" + imgUp.Tasks[functionTasks.Count - 1].Duration.ToString());
Why are we doing this?

2021-06-18 21:00 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                  CloudBlobContainer cbc = blobClient.GetContainerReference(imgUp.ContainerName);
use var and name variables properly

2021-06-18 21:01 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                              res = JsonConvert.DeserializeObject<OcrResult>(contentString);
proper name

2021-06-18 21:01 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                            functionTasks.Add(new DataSummitModels.DTO.FunctionTask("Azure OCR\tProcessed image " + imgUp.SplitImages.IndexOf(ig).ToString("000"), imgUp.Tasks[functionTasks.Count - 1]
String interpolation and name things properly. It's hard to see what this is doing

2021-06-18 21:02 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                            log.LogInformation(imgUp.Tasks[functionTasks.Count - 1].Name + ": " + imgUp.Tasks[functionTasks.Count - 1].Duration.ToString());
You're calling `imgUp.Tasks[functionTasks.Count - 1]` multiple times. Store it in a variable

2021-06-18 21:02 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                            log.LogInformation(imgUp.Tasks[functionTasks.Count - 1].Name + ": " + imgUp.Tasks[functionTasks.Count - 1].Duration.ToString());
Also, what is the logging for?

2021-06-18 21:03 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                              List<DataSummitModels.Cloud.Consolidated.Sentences> sentences = new List<DataSummitModels.Cloud.Consolidated.Sentences>();
var

Don't fully qualify `Sentences`

2021-06-18 21:03 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                              if (res != null)
Meaningful names

2021-06-18 21:04 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                                log.LogInformation(imgUp.Tasks[functionTasks.Count - 1].Name + ": " + imgUp.Tasks[functionTasks.Count - 1].Duration.ToString());
looks like variables could be used here. I also don't understand why all this logging

2021-06-18 21:04 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                log.LogInformation(imgUp.Tasks[functionTasks.Count - 1].Name + ":" + imgUp.Tasks[functionTasks.Count - 1].Duration.ToString());
As above

2021-06-18 21:05 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                  List<Task> lTPassed = new List<Task>();
var

Also, maybe a dictionary is better instead of two lists

2021-06-18 21:05 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                log.LogInformation(imgUp.Tasks[functionTasks.Count - 1].Name + ":" + imgUp.Tasks[functionTasks.Count - 1].Duration.ToString());
repeated code again

2021-06-18 21:06 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                  if (imgUp.Sentences == null) imgUp.Sentences = new List<DataSummitModels.DB.Sentence>();
ALWAYS use braces { } with `if`

2021-06-18 21:06 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
>                  //imgUp.Sentences = lResults.Where(s => s.IsUsed == true).ToList();
Commented out code is not production standard

2021-06-18 21:08 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dao/DataSummitAzureDao.cs
>              //}
Remove the whole commented code if not required

2021-06-18 21:09 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dao/DataSummitAzureDao.cs
>              var urlKey = await _context.AzureCompanyResourceUrls.SingleAsync(ar => ar.Name == name);
why `urlKey` what is it a key to?

2021-06-18 21:12 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dao/DataSummitAzureDao.cs
> +            };
I think you could possibly combine this into a single LINQ statement

2021-06-18 21:13 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dto/AzureFunctionUrlKeyDto.cs
> +    }
This class name feel wrong

2021-06-18 21:14 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dto/AzureResourceUrlKeyDto.cs
> +    public sealed class AzureResourceUrlKeyDto
I'm not sure calling this `UrlKey` is correct

2021-06-18 21:15 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dto/ImageDimensionsDto.cs
> +    public class ImageDimensionsDto
Do you intend to inherit from it?

You mark things as `sealed` to signify the can't be inherited from

2021-06-18 21:16 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Interfaces/IAzureResourcesService.cs
> +        Task<IDictionary<string, string>> GetBlobMetadata(string blobUrl);
I'd need a bit more context

2021-06-18 21:16 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Interfaces/IDataSummitDocumentsService.cs
> +        Task<KeyValuePair<string, int>> GetDocumentText(string blobUrl);
Make an object instead of using a KVP

2021-06-18 21:38 UTC, robbhudl requested changes
I'm going to address some of my review to speed things up

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
>              BlobProperties properties = await blob.GetPropertiesAsync();
var

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
> +            BlobProperties properties = await blob.GetPropertiesAsync();
var

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
> +        }
new line

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
> +        #endregion
unused

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +        private readonly IAzureResourcesService _azureResourcesService;
_azureResourcesService

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +                if (metadata.Count(m => m.Key == "IsImage" && m.Value == "true") > 0)
This looks like it could be a better LINQ expression

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +        public async Task<ImageDimensionsDto> GetDocumentImageDimensionsFromMetadata(string blobUrl)
What are we doing with these dimensions?

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +            //TODO catch error responses
??

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +                payload: "{ \"url\": \"" + blobUrl + "\"}",
string interpolation

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +            var detectedText = JsonConvert.DeserializeObject<DataSummitModels.Cloud.CognitiveServices.OCR.Application>(response);
No, I don't know why you would do that?

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +                            Width = Math.Round(width / (decimal)imageDimenions.Width, 5),
Function, try not to repeat the same code. You could also then combine with lines 169 - 172

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +            return new KeyValuePair<string, int>(blobUrl, features.Count);
Better return type

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitHelperService.cs
> +            foreach (var headerPair in headers)
`header` rather than `headerPair`

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Application.cs
> +    public class Application
I can't see why this is called `Application`

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Lines.cs
> +    public class Lines
This class name doesn't help me understand what this object does

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Words.cs
> +    public class Words
I think we can name these better

2021-06-18 21:38 UTC, robbhudl commented on DataSummitSolution/DataSummitWeb/Controllers/DocumentsController.cs
> +        [HttpPost("textRecoginition")]
more descriptive name - our other endpoints tell us what they do, this doesn't

2021-06-18 22:34 UTC, robbhudl commented on DataSummitSolution/AzureFunctions/RecogniseText/Azure.cs
> +                functionTasks.Add(new DataSummitModels.DTO.FunctionTask("Azure OCR\tGet container", imgUp.Tasks[functionTasks.Count - 1].TimeStamp));
@TomJamesAtDataSummit surely `functionTasks.Count - 1` would be `-1` at this point, given you've only just created a new list?

2021-06-18 23:01 UTC, robbhudl commented
@TomJamesAtDataSummit we also need to sort out these weird classes that you have created using inheritance e.g.

public partial class ImageGrids : ImageGrid
    {
        public Image Image { get; set; }
        public List<Sentence> Sentences { get; set; } = new List<Sentence>();
        public DocumentContentType DocumentType { get; set; } = DocumentContentType.Unknown;
        public ImageType ImageType { get; set; } = ImageType.Unknown;

        public ImageGrids()
        { ; }
    }

2021-06-19 09:52 UTC, robbhudl commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Application.cs
> +    public class Application
This class has been created to deserialise a response from a Microsoft endpoint

If we can change the name it would be good!

2021-06-21 13:10 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Dto/ImageDimensionsDto.cs
> +    public class ImageDimensionsDto
I was following one of your previous examples. I can't see a situation where this would be inherited though.

2021-06-21 13:26 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Interfaces/IAzureResourcesService.cs
> +        Task<IDictionary<string, string>> GetBlobMetadata(string blobUrl);
`List<KeyPairValue<string, string>>` was used in one our similar methods. I don't know if http request headers must have a unique key name. This was only raised to see if it were better to try and remain consistent across our methods. Or is it better follow the external end-point's return type?

2021-06-21 13:32 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Interfaces/IDataSummitDocumentsService.cs
> +        Task<KeyValuePair<string, int>> GetDocumentText(string blobUrl);
This seems to make a the output less predictable (looser). What's the theory behind that?

2021-06-21 13:36 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +        public async Task<ImageDimensionsDto> GetDocumentImageDimensionsFromMetadata(string blobUrl)
Making the positions of any feature a ratio of 1 and not an absolute value that can change many different ways, depending on a process. Best example is varying the DPI on a rasterizer. Width = 200 pixels @ 150dpi; Width = 400 pixels @ 300dpi. Literally the same input.

2021-06-21 13:37 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +            //TODO catch error responses
This was a comment that existed from a previous end-point. Is it still relevant or should the comment just be deleted? It should be addressed, to reduce tech-debt.

2021-06-21 13:44 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Dao/DataSummitAzureDao.cs
>              var urlKey = await _context.AzureCompanyResourceUrls.SingleAsync(ar => ar.Name == name);
`url` references to the end-point location.
`key` is the DevOps resource security.

Azure Functions take the `key` as an `url` parameter. Cognitive Services take the `key` as a http request header entry.

2021-06-21 13:54 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Dto/AzureResourceUrlKeyDto.cs
> +    public sealed class AzureResourceUrlKeyDto
It returns a `url` and `key` from our database for a particular DevOps resource end-point.

2021-06-21 13:55 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Dto/AzureFunctionUrlKeyDto.cs
> +    }
It returns a `url` and `key` from our database for a particular DevOps resource end-point. Seems to indicate it's purpose. Can you suggest something that's more obvious!?!

2021-06-21 13:55 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Dao/DataSummitAzureDao.cs
> +            };
Do you mean:
`return await _context.AzureCompanyResourceUrls.SingleAsync(ar => ar.Name == name && ar.ResourceType == type);`

2021-06-21 13:56 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
>              BlobProperties properties = await blob.GetPropertiesAsync();
`var` doesn't cast it correctly, hence my comment. I tried it and the compiler throw errors. Microsoft's code, note mine.

2021-06-21 13:57 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
> +            BlobProperties properties = await blob.GetPropertiesAsync();
var doesn't cast it correctly, hence my comment. I tried it and the compiler throw errors. Microsoft's code, note mine.

2021-06-21 13:58 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
> +        #endregion
Deleted

2021-06-22 10:53 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
> +        }
Removed

2021-06-22 15:49 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dto/ImageDimensionsDto.cs
> +    public class ImageDimensionsDto
Then you can mark it as `sealed` if you want. To be honest it doesn't really matter and isn't too important at this point.

2021-06-22 15:52 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Interfaces/IAzureResourcesService.cs
> +        Task<IDictionary<string, string>> GetBlobMetadata(string blobUrl);
One is an interface, so as long as the concrete type that gets used complies, we're fine. Interfaces are generally good, so you are fine to stick with what Microsoft use.
A "similar" method may not be doing the same thing, it's all always about context, rather than spotting and copying patterns

2021-06-22 15:55 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Interfaces/IDataSummitDocumentsService.cs
> +        Task<KeyValuePair<string, int>> GetDocumentText(string blobUrl);
I don't follow what you mean? What I am suggesting makes the output more obvious as we will have a type with a meaningful name.

It doesn't feel to me that it is a key - value pair at all, rather two properties on the same object. Hence why a type is better. If we end up with more properties in future, the method signature doesn't have to change

2021-06-22 15:56 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +        public async Task<ImageDimensionsDto> GetDocumentImageDimensionsFromMetadata(string blobUrl)
More specifically - where are we actually using them?

If something is outside the scope of a user story - don't bring it in or do it until _after_ agreeing it is in scope

2021-06-22 15:58 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +            //TODO catch error responses
Get rid of it if it is bothering you.

> It should be addressed, to reduce tech-debt.

I disagree. It is not part of this ticket, so should not be addressed here. 
It can be addressed in its own tech debt ticket. There is far more tech debt that has been created elsewhere that is much higher priority.

2021-06-22 16:06 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dto/AzureFunctionUrlKeyDto.cs
> +    }
If it contained 3 or more parameters would you add all 3+ parameters into the class name? I'm not sure you would.

Your description `DevOpsResourceDto` seems more descriptive

If it is a DevOps resource and is not always an AzureFunction then naming it as one is bad.

Alternatively, how about `AzureFunctionEndpointDto`?

2021-06-22 16:07 UTC, robbhudl commented on DataSummitSolution/DataSummitHelper/Dto/AzureResourceUrlKeyDto.cs
> +    public sealed class AzureResourceUrlKeyDto
That doesn't make it a good name. If it contained 3 or more parameters would you add all 3+ parameters into the class name? I'm not sure you would.

2021-07-11 10:51 UTC, LightosTomJ commented on DataSummitSolution/DataSummitHelper/Interfaces/IDataSummitDocumentsService.cs
> +        Task<KeyValuePair<string, int>> GetDocumentText(string blobUrl);
DocumentFeatureDto created

2021-07-11 10:53 UTC, LightosTomJ commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +        public async Task<ImageDimensionsDto> GetDocumentImageDimensionsFromMetadata(string blobUrl)
Per our conversations, this is in scope otherwise correct functionality cannot be created.

2021-07-11 10:57 UTC, LightosTomJ commented on DataSummitSolution/DataSummitHelper/Dto/AzureFunctionUrlKeyDto.cs
> +    }
`AzureFunctionEndpointDto` created

2021-07-11 10:58 UTC, LightosTomJ commented on DataSummitSolution/DataSummitHelper/Dto/AzureResourceUrlKeyDto.cs
> +    public sealed class AzureResourceUrlKeyDto
`AzureResourceEndpointDto` created

2021-07-11 11:04 UTC, LightosTomJ commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
>              BlobProperties properties = await blob.GetPropertiesAsync();
Explicit cast removed

2021-07-11 11:05 UTC, LightosTomJ commented on DataSummitSolution/DataSummitHelper/Services/AzureResourcesService.cs
> +            BlobProperties properties = await blob.GetPropertiesAsync();
Explicit cast removed for `blob.GetPropertiesAsync()`

2021-07-12 12:29 UTC, LightosTomJ commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Lines.cs
> +    public class Lines
`LinesOfText`? FYI, these are not sentences, as a sentence may cross multiple lines.

2021-07-12 12:30 UTC, LightosTomJ commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Application.cs
> +    public class Application
What takes you fancy:
- `Image`
- `FromImage`
- `Page`
- `FromPage`

2021-07-12 12:31 UTC, LightosTomJ commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Words.cs
> +    public class Words
I can't!!! What describes a word better than the word `word`? Can you suggest a preference?

2021-07-12 12:32 UTC, LightosTomJ commented on DataSummitSolution/DataSummitWeb/Controllers/DocumentsController.cs
> +        [HttpPost("textRecoginition")]
- `OCR`
- `RecogniseText`

2021-07-16 11:30 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +        public async Task<ImageDimensionsDto> GetDocumentImageDimensionsFromMetadata(string blobUrl)
Image dimensions are now being captured within the `uploadFiles` API end-point. These are successfully persisting in the database.

2021-07-16 11:32 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Dao/DataSummitAzureDao.cs
> +            };
@THEgaDJet, can you combine these into a single linq command, I do not know how to do this?

2021-07-16 11:41 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +                if (metadata.Count(m => m.Key == "IsImage" && m.Value == "true") > 0)
Document image dimensions info captured within `uploadFiles` API end-point and stored within database. Dimension data now fetched from database for OCR location to be made 'parameter-less'. The above method has been removed.

2021-07-16 11:45 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +                payload: "{ \"url\": \"" + blobUrl + "\"}",
`{` curly brackets prevent easy string interpolation implementation.

2021-07-16 11:47 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitHelper/Services/DataSummitDocumentsService.cs
> +                            Width = Math.Round(width / (decimal)imageDimenions.Width, 5),
Ignored for now. This isn't the last time that these numeric adjustments will occur. `//TODO` comment added for another User Story

2021-07-16 11:48 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Application.cs
> +    public class Application
This needs to be part of a different User Story, names and JSON mappings are too large for this PR.

2021-07-16 11:49 UTC, TomJamesAtDataSummit commented on DataSummitSolution/DataSummitModels/Cloud/CognitiveServices/OCR/Lines.cs
> +    public class Lines
This needs to be part of a different User Story, names and JSON mappings are too large for this PR.

2021-08-02 16:59 UTC, robbhudl approved these changes

2021-08-03 20:50 UTC, merged